### PR TITLE
Fix: Uses Provider<ResolvedComponentResult> as input to Task

### LINKED ISSUE #67: Issue after 0.4.0 Release
I'm monitoring the buildscript classpath, and after bumping to `0.4.0`, it correctly detects there was a change.  HOWEVER, if I do run the `./gradlew :dependencyGuardBaseline` task it does not create a new baseline file and just continues to show the error.

```
* What went wrong:
Execution failed for task ':buildSrc:dependencyGuard'.
> Dependencies Changed in : for configuration classpath
  - com.dropbox.dependency-guard:com.dropbox.dependency-guard.gradle.plugin:0.3.1
  + com.dropbox.dependency-guard:com.dropbox.dependency-guard.gradle.plugin:0.4.0
  - com.dropbox.dependency-guard:dependency-guard:0.3.1
  + com.dropbox.dependency-guard:dependency-guard:0.4.0
  
  If this is intentional, re-baseline using ./gradlew :dependencyGuardBaseline
  Or use ./gradlew dependencyGuardBaseline to re-baseline dependencies in entire project.
```

I then deleted the `rm dependencies/classpath.txt ` file and re-ran the baseline task, but am seeing the same issue.  I additionally attempted to add `--no-configuration-cache` and it still doesn't work as expected.  No new baseline file is created, and the same error above is shown.

### PR DESCRIPTION
**Pull request by handstandsam**
Following documentation on config cache https://docs.gradle.org/current/userguide/configuration_cache.html

Hopefully fixes #67 and #68

---

Chose to drop support for Gradle 7.3.x.  `resolutionRoot` was unavailable prior to Gradle 7.4.
Screen Shot 2023-01-23 at 10 14 32 AM

### CODE REVIEW

File: dependency-guard/src/gradleTest/kotlin/com/dropbox/gradle/plugins/dependencyguard/GradleVersionArgumentsProvider.kt [hunk 1]
```diff
@@ -10,7 +10,6 @@ class GradleVersionArgumentsProvider : ArgumentsProvider {
 
     override fun provideArguments(context: ExtensionContext?): Stream<out Arguments> = Stream
         .of(
-            ParameterizedPluginArgs(gradleVersion = GradleVersion.version("7.3.3"), withConfigurationCache = false),
```
Comment (handstandsam) [inline dependency-guard/src/gradleTest/kotlin/com/dropbox/gradle/plugins/dependencyguard/GradleVersionArgumentsProvider.kt:13]: Test fails for 7.3 because `resolutionRoot` is not available in this version.

File: dependency-guard/src/main/kotlin/com/dropbox/gradle/plugins/dependencyguard/DependencyGuardPlugin.kt [hunk 2]
```diff
@@ -16,14 +16,16 @@ public class DependencyGuardPlugin : Plugin<Project> {
...
+
         internal const val DEPENDENCY_GUARD_TASK_NAME = "dependencyGuard"
 
         internal const val DEPENDENCY_GUARD_BASELINE_TASK_NAME = "dependencyGuardBaseline"
     }
 
     override fun apply(target: Project) {
         val extension = target.extensions.create(
-            DEPENDENCY_GUARD_TASK_NAME,
+            DEPENDENCY_GUARD_EXTENSION_NAME,
```
Comment (handstandsam) [inline dependency-guard/src/main/kotlin/com/dropbox/gradle/plugins/dependencyguard/DependencyGuardPlugin.kt:28]: This change is not required in this diff, but is zero risk and slightly more explicit.

File: dependency-guard/src/main/kotlin/com/dropbox/gradle/plugins/dependencyguard/internal/ConfigurationValidators.kt [hunk 3]
```diff
@@ -27,23 +27,23 @@ internal object ConfigurationValidators {
...
-        }
-        val configurationNames = monitoredConfigurations.map { it.configurationName }
-        require(configurationNames.isNotEmpty() && configurationNames[0].isNotBlank()) {
-            StringBuilder().apply {
-                appendLine("Error: No configurations provided to Dependency Guard Plugin.")
-                appendLine("Here are some valid configurations you could use.")
-                appendLine("")
-                val availableConfigNames = availableConfigurations
-                    .filter { isClasspathConfig(it) }
+        } else {
```
Comment (handstandsam) [inline dependency-guard/src/main/kotlin/com/dropbox/gradle/plugins/dependencyguard/internal/ConfigurationValidators.kt:30]: We were using the `return` at the end of the `if` block, but `if/else` reads better IMO as this is an exahaustive `if/else`

File: dependency-guard/src/main/kotlin/com/dropbox/gradle/plugins/dependencyguard/internal/ProjectExt.kt [hunk 4]
```diff
@@ -19,8 +20,8 @@ internal val Project.projectConfigurations: ConfigurationContainer
         configurations
     }
 
-internal fun ConfigurationContainer.getResolvedComponentResult(name: String): ResolvedComponentResult = this
+internal fun ConfigurationContainer.getResolvedComponentResult(name: String): Provider<ResolvedComponentResult> = this
```
Comment (handstandsam) [inline dependency-guard/src/main/kotlin/com/dropbox/gradle/plugins/dependencyguard/internal/ProjectExt.kt:23]: Using recommended pattern in Config Cache Documentation: https://docs.gradle.org/current/userguide/configuration_cache.html
Screen Shot 2023-01-23 at 10 17 39 AM

File: dependency-guard/src/main/kotlin/com/dropbox/gradle/plugins/dependencyguard/internal/list/DependencyGuardListTask.kt [hunk 5]
```diff
@@ -57,7 +58,7 @@ internal abstract class DependencyGuardListTask : DefaultTask() {
     abstract val projectPath: Property<String>
 
     @get:Input
-    abstract val monitoredConfigurationsMap: MapProperty<DependencyGuardConfiguration, ResolvedComponentResult>
+    abstract val monitoredConfigurationsMap: MapProperty<DependencyGuardConfiguration, Provider<ResolvedComponentResult>>
```
Comment (handstandsam) [inline dependency-guard/src/main/kotlin/com/dropbox/gradle/plugins/dependencyguard/internal/list/DependencyGuardListTask.kt:61]: Using recommended pattern in Config Cache Documentation: https://docs.gradle.org/current/userguide/configuration_cache.html
Screen Shot 2023-01-23 at 10 17 39 AM
